# Base image
FROM python:3.11-slim

# Set working directory
WORKDIR /ui

# Install Python dependencies
COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir --timeout 300 -r requirements.txt


# Copy Streamlit UI code
COPY app/UI ./app/UI

# Expose Streamlit port
EXPOSE 8501

# Run Streamlit
CMD ["streamlit", "run", "app/UI/ui.py", "--server.port=8501", "--server.address=0.0.0.0"]
